name: Dynamic Jobs Based on Actor

on:
  push:
    branches:
      - main

jobs:
  dynamic_jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        actor: [user1, user2, user3]  # Add GitHub actor profile names here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Perform Workflow Actions
        run: |
          if [ "${{ github.actor }}" == "${{ matrix.actor }}" ]; then
            echo "Performing actions for actor: ${{ matrix.actor }}"
            # Add your workflow steps here
          else
            echo "Skipping actions for actor: ${{ matrix.actor }}"
          fi
