on:
  workflow_dispatch:
    inputs:
      aab_generation:
        description: 'Generate AAB'
        required: false
        default: 'false'
      build_runner_build:
        description: 'Build Runner Build'
        required: false
        default: 'false'
      change_splash:
        description: 'Change Splash'
        required: false
        default: 'false'
      i18n_generation:
        description: 'Generate i18n'
        required: false
        default: 'false'
      generate_launcher_icons:
        description: 'Generate Launcher Icons'
        required: false
        default: 'false'
      custom_app_name:
        description: 'Custom App Name (Leave empty to skip)'
        required: false
      custom_package_name:
        description: 'Custom Package Name (Leave empty to skip)'
        required: false
jobs:
  manual_dispatch:
    runs-on: macos-latest
    run-name: ${{ github.actor }}
