on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        branch: [main, develop]

    steps:
      - name: Set workflow run name
        run: |
          github.actions.workflow_run.update({
            name: "Build ${github.ref_name}"
          })

      # ...
